import csv
import json
import re

file_path = r'c:\Users\Gabriel Amorim\Desktop\APPS ANTIGRAVITY\Rota Disney\public\Disney Cinemas- CONSULTOR 04 - SP base 1csv.csv'

def clean_name(name):
    replacements = {
        'Cï¾ƒæ³¥IGO': 'codigo',
        'RAZï¾ƒã‚°': 'razao',
        'ENDEREï¾ƒï¿½O': 'endereco',
        'RESPONSï¾ƒã€ƒEL': 'responsavel',
        'PRECISï¾ƒã‚°': 'precisao',
        'REGIï¾ƒã‚°': 'regiao',
        'ELETRï¾ƒå¹´ICA': 'eletronica',
        ' ': '_',
        '.': '',
        '-': '_',
        '/': '_',
        '(': '',
        ')': '',
        'ã€ƒ': '',
        'ï¿½': 'o',
        'ï¾ƒæ³¥': 'o',
        'ï¾ƒã‚°': 'ao',
        'ï¾ƒã€ƒ': 've'
    }
    name = name.strip().upper()
    for k, v in replacements.items():
        name = name.replace(k, v)
    name = re.sub(r'[^a-zA-Z0-9_]', '', name.lower())
    return name or 'column'

try:
    with open(file_path, 'r', encoding='latin1') as f:
        # Read header
        header_raw = f.readline().strip()
        # Full split ignoring quotes for now then cleanup
        raw_headers = header_raw.split(';')
        headers = []
        counts = {}
        for h in raw_headers:
            h = h.strip('" ')
            if not h: continue
            hc = clean_name(h)
            if hc in counts:
                counts[hc] += 1
                hc = f"{hc}_{counts[hc]}"
            else:
                counts[hc] = 1
            headers.append(hc)
            
        print(f"-- Table creation script generated by script")
        print(f"CREATE TABLE IF NOT EXISTS lojas_cinema (")
        print(f"  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,")
        print(f"  created_at TIMESTAMPTZ DEFAULT NOW(),")
        for h in headers:
            print(f"  {h} TEXT,")
        print(f");\n")
        
        # Prepare data for INS-ERT
        # We'll generate a batch of inserts
        all_data = []
        for line in f:
            if not line.strip(): continue
            # Split and clean each field
            # Use regex to split by ; but handle the quoted parts
            # Actually, the quickest way for this specific weird format is:
            # remove all quotes, then split by ;
            line = line.replace('"', '').strip()
            row = line.split(';')
            # Pad or trim to match header length
            row = row[:len(headers)]
            while len(row) < len(headers):
                row.append('')
            
            # Escape single quotes for SQL
            row = [r.replace("'", "''") for r in row]
            all_data.append(row)
            
        # Write SQL in chunks
        chunk_size = 50
        for i in range(0, len(all_data), chunk_size):
            chunk = all_data[i:i+chunk_size]
            cols = ", ".join(headers)
            print(f"INSERT INTO lojas_cinema ({cols}) VALUES")
            vals_list = []
            for row in chunk:
                vals = "', '".join(row)
                vals = f"('{vals}')"
                vals_list.append(vals)
            print(",\n".join(vals_list) + ";\n")

except Exception as e:
    import sys
    print(f"Error: {e}", file=sys.stderr)
